Last login: Tue Dec 15 18:16:08 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Charlies-MacBook-Pro:~ charlieumali$ ssh cumali@104.40.3.67
Enter passphrase for key '/Users/charlieumali/.ssh/id_rsa': 
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1032-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Dec 16 03:01:03 UTC 2020

  System load:  0.0                Processes:              120
  Usage of /:   10.3% of 28.90GB   Users logged in:        0
  Memory usage: 38%                IP address for eth0:    10.0.0.4
  Swap usage:   0%                 IP address for docker0: 172.17.0.1

 * Introducing self-healing high availability clusters in MicroK8s.
   Simple, hardened, Kubernetes for production, from RaspberryPi to DC.

     https://microk8s.io/high-availability

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

3 packages can be updated.
0 updates are security updates.


*** System restart required ***
Last login: Thu Dec 10 07:04:17 2020 from 76.167.173.98
cumali@JumpBoxProvisioner:~$ ls
cumali@JumpBoxProvisioner:~$ ls
cumali@JumpBoxProvisioner:~$ dir
cumali@JumpBoxProvisioner:~$ sudo docker start happy_lewin
happy_lewin
cumali@JumpBoxProvisioner:~$ sudo docker attach  happy_lewin
root@ce27bc4b4dca:~# ls
metricbeat-7.6.1-amd64.deb
root@ce27bc4b4dca:~# cd ansible
bash: cd: ansible: No such file or directory
root@ce27bc4b4dca:~# ls
metricbeat-7.6.1-amd64.deb
root@ce27bc4b4dca:~# cd /etc/ansible/
root@ce27bc4b4dca:/etc/ansible# ls
ansible.cfg  filebeat-playbook.yml  files  hosts  install-elk.yml  metricbeat_copy.yml  pentest.yml  roles
root@ce27bc4b4dca:/etc/ansible# git clone https://github.com/charlieumali/Cybersecurity.git
bash: git: command not found
root@ce27bc4b4dca:/etc/ansible# exit
exit
cumali@JumpBoxProvisioner:~$ sudo docker attach  happy_lewin
You cannot attach to a stopped container, start it first
cumali@JumpBoxProvisioner:~$ sudo docker start happy_lewin
happy_lewin
cumali@JumpBoxProvisioner:~$ sudo docker attach  happy_lewin
root@ce27bc4b4dca:~# clear

root@ce27bc4b4dca:~# ls
metricbeat-7.6.1-amd64.deb
root@ce27bc4b4dca:~# cd /etc/ansible/
root@ce27bc4b4dca:/etc/ansible# ls 
ansible.cfg  filebeat-playbook.yml  files  hosts  install-elk.yml  metricbeat_copy.yml  pentest.yml  roles
root@ce27bc4b4dca:/etc/ansible# cat filebeat-playbook.yml 
---
- name: Installing and Launch Filebeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    # Use command module
  - name: Install filebeat .deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

    # Use copy module
  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

    # Use command module
  - name: Enable and Configure System Module
    command: filebeat modules enable system

    # Use command module
  - name: Setup filebeat
    command: filebeat setup

    # Use command module
  - name: Start filebeat service
    command: service filebeat start

root@ce27bc4b4dca:/etc/ansible# cat install-elk.yml 
---
- name: Configure Elk VM with Docker
  hosts: elk
  remote_user: cumali
  become: true
  tasks:
    # Use apt module
    - name: docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

      # Use apt module
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

      # Use pip module (It will default to pip3)
    - name: Install Docker module
      pip:
        name: docker
        state: present

      # Use command module
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

      # Use sysctl module
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

      # Use docker_container module
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044

root@ce27bc4b4dca:/etc/ansible# ls
ansible.cfg  filebeat-playbook.yml  files  hosts  install-elk.yml  metricbeat_copy.yml  pentest.yml  roles
root@ce27bc4b4dca:/etc/ansible# nano metricbeat_copy.yml 
root@ce27bc4b4dca:/etc/ansible# nano metricbeat_copy.yml 

  GNU nano 2.9.3                                                                               metricbeat_copy.yml                                                                                          

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

#============================== X-Pack Monitoring ===============================
# metricbeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

# Set to true to enable the monitoring reporter.
#monitoring.enabled: false

# Sets the UUID of the Elasticsearch cluster under which monitoring data for this
# Metricbeat instance will appear in the Stack Monitoring UI. If output.elasticsearch
# is enabled, the UUID is derived from the Elasticsearch cluster referenced by output.elasticsearch.
#monitoring.cluster_uuid:

# Uncomment to send the metrics to Elasticsearch. Most settings from the
# Elasticsearch output are accepted here as well.
# Note that the settings should point to your Elasticsearch *monitoring* cluster.
# Any setting that is not set is automatically inherited from the Elasticsearch
# output configuration, so if you have the Elasticsearch output configured such
# that it is pointing to your Elasticsearch monitoring cluster, you can simply
# uncomment the following line.
#monitoring.elasticsearch:

#================================= Migration ==================================

# This allows to enable 6.7 migration aliases
#migration.6_to_7.enabled: true
